common:
  run_label: "run10000_3000_coco"
  accum_freq: 1
  accum_after_epoch: -1
  log_freq: 500
  auto_resume: true
  mixed_precision: false
  results_loc: "result"
dataset:
  # root_train: "imgs_det"
  # root_val: "imgs_det"
  name: "krsbi_ssd"
  category: "detection"
  train_batch_size0: 64
  val_batch_size0: 64
  workers: -1
  persistent_workers: true
  pin_memory: true
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 224
    crop_size_height: 224
loss:
  category: "detection"
  detection:
    name: "ssd_multibox_loss"
    ssd_multibox_loss:
      neg_pos_ratio: 3
optim:
  name: "adamw"
  weight_decay: 0.02
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 10000
  warmup_iterations: 500
  warmup_init_lr: 0.00009
  cosine:
    max_lr: 0.0009
    min_lr: 0.000009 # 1.e-6 # 0.000001
model:
  detection:
    name: "ssd"
    is_training: true
    ssd:
      anchors_aspect_ratio: [ [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [2] ]
      output_strides: [ 16, 32, 64, 128, 256, -1 ]
      proj_channels: [512, 256, 256, 128, 128, 64]
      center_variance: 0.1
      size_variance: 0.2
      iou_threshold: 0.5
      nms_iou_threshold: 0.5
    pretrained: "/home/labai/eky_edgeformer/checkpoints/checkpoint_coco_modif.pt"
    n_classes: 4
  classification:
    name: "edgeformer"
    classifier_dropout: 0.2
    # pretrained: "/content/drive/MyDrive/skripsi/result/checkpoint/cls/checkpoint_last_93.pt"
    edge:
      scale: "scale_s"
      mode: "outer_frame_v1"
      kernel: "gcc_ca"
      fusion: "concat"
      instance_kernel: "interpolation_bilinear"
      use_pe: True
    activation:
      name: "swish"
  normalization:
    name: "batch_norm_2d"
    momentum: 0.1
  activation:
    name: "relu" # If specific activation function is not specified, this one will be used as a default
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
    conv_weight_std: false
# ema:
#   enable: True
#   momentum: 0.0005
ddp:
  enable: True
  rank: 0
  world_size: -1
  dist_port: 30787
stats:
  name: [ "loss" ]
  checkpoint_metric: "loss"
  checkpoint_metric_max: false
# image_augmentation:
#   random_horizontal_flip: 
#     enable: True
#   random_gauss_noise:
#     enable: True
#   random_gamma_correction:
#     enable: True
# evaluation:
#   detection:
#     mode: "image_folder"
#     path: "/content/drive/MyDrive/skripsi/imgs_det/balance/images/test"